"""empty message

Revision ID: 0351c04e3cb1
Revises: 24c624517717
Create Date: 2021-09-09 19:46:18.831722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0351c04e3cb1'
down_revision = '24c624517717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('description', sa.String(length=300), nullable=True))
    op.drop_column('quiz', 'decription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('decription', sa.VARCHAR(length=300), nullable=True))
    op.drop_column('quiz', 'description')
    # ### end Alembic commands ###
