"""empty message

Revision ID: 2a3a0a6e6755
Revises: 0351c04e3cb1
Create Date: 2021-09-11 03:50:43.051561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3a0a6e6755'
down_revision = '0351c04e3cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('choice_1', sa.String(), nullable=True))
    op.add_column('question', sa.Column('choice_2', sa.String(), nullable=True))
    op.add_column('question', sa.Column('choice_3', sa.String(), nullable=True))
    op.add_column('question', sa.Column('choice_4', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'choice_4')
    op.drop_column('question', 'choice_3')
    op.drop_column('question', 'choice_2')
    op.drop_column('question', 'choice_1')
    # ### end Alembic commands ###
