"""empty message

Revision ID: 42d2e4eab0b0
Revises: 717d27a25eca
Create Date: 2021-09-14 02:34:52.886989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d2e4eab0b0'
down_revision = '717d27a25eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_user_answer', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_user_answer', 'quiz', ['quiz_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_user_answer', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_user_answer', 'user', ['quiz_id'], ['id'])
    # ### end Alembic commands ###
