"""empty message

Revision ID: 66e129c9f9e1
Revises: ae4af0727798
Create Date: 2021-09-19 23:28:57.101622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e129c9f9e1'
down_revision = 'ae4af0727798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_user_answer', sa.Column('quiz_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quiz_user_answer', 'quiz', ['quiz_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_user_answer', type_='foreignkey')
    op.drop_column('quiz_user_answer', 'quiz_id')
    # ### end Alembic commands ###
