"""empty message

Revision ID: 717d27a25eca
Revises: 2a3a0a6e6755
Create Date: 2021-09-14 02:31:11.251003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717d27a25eca'
down_revision = '2a3a0a6e6755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_user_answer', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_user_answer', 'quiz', ['quiz_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_user_answer', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_user_answer', 'user', ['quiz_id'], ['id'])
    # ### end Alembic commands ###
