"""Initial Migration

Revision ID: 817f6751aa3c
Revises: 
Create Date: 2021-08-20 02:19:45.056005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817f6751aa3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
