"""empty message

Revision ID: 8c05e794e916
Revises: e06e18c3b88e
Create Date: 2021-09-21 00:18:38.896647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c05e794e916'
down_revision = 'e06e18c3b88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_user_answer', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['id'])

    with op.batch_alter_table('quiz_user_taken', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_user_taken', schema=None) as batch_op:
        batch_op.drop_column('total')

    with op.batch_alter_table('quiz_user_answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
