"""empty message

Revision ID: 9162ac6a279d
Revises: 42d2e4eab0b0
Create Date: 2021-09-14 02:42:55.991079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9162ac6a279d'
down_revision = '42d2e4eab0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_user_answer', type_='foreignkey')
    op.drop_column('quiz_user_answer', 'quiz_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_user_answer', sa.Column('quiz_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'quiz_user_answer', 'user', ['quiz_id'], ['id'])
    # ### end Alembic commands ###
