"""empty message

Revision ID: aee99fbfc078
Revises: 4c4f311fc107
Create Date: 2021-09-21 03:22:15.396903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee99fbfc078'
down_revision = '4c4f311fc107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_user_answer', sa.Column('expected', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_user_answer', type_='foreignkey')
    op.drop_column('quiz_user_answer', 'expected')
    # ### end Alembic commands ###
