"""empty message

Revision ID: e06e18c3b88e
Revises: 1c6724696f49
Create Date: 2021-09-21 00:11:09.008146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06e18c3b88e'
down_revision = '1c6724696f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'quiz_user_answer', 'quiz', ['quiz_id'], ['id'])
    op.add_column('quiz_user_taken', sa.Column('user_total', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_user_taken', 'user_total')
    op.drop_constraint(None, 'quiz_user_answer', type_='foreignkey')
    # ### end Alembic commands ###
