"""empty message

Revision ID: f78a46b417b5
Revises: 66e129c9f9e1
Create Date: 2021-09-21 00:01:45.778284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78a46b417b5'
down_revision = '66e129c9f9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'quiz_user_answer', 'quiz', ['quiz_id'], ['id'])
    op.add_column('quiz_user_taken', sa.Column('user_total', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_user_taken', 'user_total')
    op.drop_constraint(None, 'quiz_user_answer', type_='foreignkey')
    # ### end Alembic commands ###
